---
- name: all copy ansible_os_family
  hosts:  all
  become: true

  tasks:
  - name: copy file
    copy: 
      src: /home/ubuntu/akshay.txt
      dest: /tmp
      mode: '777'
      backup: true
...        