---
- name: all copy ansible_os_family
  hosts:  all

  tasks:
  - name: copy file
    copy: 
      src: /home/akshay
      dest: /tmp
      owner: 'Ubuntu'
      group: 'Ubuntu'
      mode: 0777
      backup: true
...        