---
- name: Example Playbook
  hosts: your_target_hosts
  become: yes  # Optionally, if you need to execute commands with elevated privileges
  
  tasks:
    - name: Ensure a package is installed
      package:
        name: package_name
        state: present
  
    - name: Ensure a service is running
      service:
        name: service_name
        state: started
        enabled: yes  # Ensure the service starts on boot
  
    - name: Ensure a directory exists
      file:
        path: /path/to/your/directory
        state: directory
        owner: your_user
        group: your_group
        mode: "0755"  # Optional: Set permissions
  
    - name: Copy a file
      copy:
        src: /path/to/source/file
        dest: /path/to/destination/file
        owner: your_user
        group: your_group
        mode: "0644"  # Optional: Set permissions
