---
- name: Prompt Playbook Example
  hosts: localhost
  vars_prompt:
    - name: user_name
      prompt: "Enter your name:"
      private: no

  tasks:
    - name: Print user input
      debug:
        msg: "Hello, {{ user_name }}!"
